package com.appsdeveloperblog.app.ws.ui.model.response;

/**
 * Creates objects which will be used by the framework to
 * create JSON payloads which will be sent in response to a
 * client, confirming successful persistence of user data
 * to the database
 *
 * @see com.appsdeveloperblog.app.ws.ui.model.response.UserResponseModel
 * @see com.appsdeveloperblog.app.ws.io.entity.UserEntity
 *
 * @author Omar Hussain
 */
public class UserResponseModel {
    // This is a public user ID, different from the autogenerated
    // ID stored in the database. This is to prevent malicious
    // agents from having access to sensitive information.
    private String userId;
    private String firstName;
    private String lastName;
    private String email;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
